/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ColumnFilterData
import org.openapitools.client.models.FilterData

class ColumnFilterDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ColumnFilterData
        //val modelInstance = ColumnFilterData()

        // to test the property `column`
        should("test column") {
            // uncomment below to test the property
            //modelInstance.column shouldBe ("TODO")
        }

        // to test the property `filters`
        should("test filters") {
            // uncomment below to test the property
            //modelInstance.filters shouldBe ("TODO")
        }

    }
}
