/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.Component
import org.openapitools.client.models.Survey

class ComponentTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Component
        //val modelInstance = Component()

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `key`
        should("test key") {
            // uncomment below to test the property
            //modelInstance.key shouldBe ("TODO")
        }

        // to test the property `new`
        should("test new") {
            // uncomment below to test the property
            //modelInstance.new shouldBe ("TODO")
        }

        // to test the property `sequenceNo`
        should("test sequenceNo") {
            // uncomment below to test the property
            //modelInstance.sequenceNo shouldBe ("TODO")
        }

        // to test the property `survey`
        should("test survey") {
            // uncomment below to test the property
            //modelInstance.survey shouldBe ("TODO")
        }

        // to test the property `text`
        should("test text") {
            // uncomment below to test the property
            //modelInstance.text shouldBe ("TODO")
        }

    }
}
