/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetAccountsTimeline

class GetAccountsTimelineTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetAccountsTimeline
        //val modelInstance = GetAccountsTimeline()

        // to test the property `activatedDate`
        should("test activatedDate") {
            // uncomment below to test the property
            //modelInstance.activatedDate shouldBe ("TODO")
        }

        // to test the property `approvedByFirstname`
        should("test approvedByFirstname") {
            // uncomment below to test the property
            //modelInstance.approvedByFirstname shouldBe ("TODO")
        }

        // to test the property `approvedByLastname`
        should("test approvedByLastname") {
            // uncomment below to test the property
            //modelInstance.approvedByLastname shouldBe ("TODO")
        }

        // to test the property `approvedByUsername`
        should("test approvedByUsername") {
            // uncomment below to test the property
            //modelInstance.approvedByUsername shouldBe ("TODO")
        }

        // to test the property `approvedDate`
        should("test approvedDate") {
            // uncomment below to test the property
            //modelInstance.approvedDate shouldBe ("TODO")
        }

        // to test the property `submittedByFirstname`
        should("test submittedByFirstname") {
            // uncomment below to test the property
            //modelInstance.submittedByFirstname shouldBe ("TODO")
        }

        // to test the property `submittedByLastname`
        should("test submittedByLastname") {
            // uncomment below to test the property
            //modelInstance.submittedByLastname shouldBe ("TODO")
        }

        // to test the property `submittedByUsername`
        should("test submittedByUsername") {
            // uncomment below to test the property
            //modelInstance.submittedByUsername shouldBe ("TODO")
        }

        // to test the property `submittedOnDate`
        should("test submittedOnDate") {
            // uncomment below to test the property
            //modelInstance.submittedOnDate shouldBe ("TODO")
        }

    }
}
