/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetCentersCenterIdResponse
import org.openapitools.client.models.GetCentersStatus

class GetCentersCenterIdResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetCentersCenterIdResponse
        //val modelInstance = GetCentersCenterIdResponse()

        // to test the property `active`
        should("test active") {
            // uncomment below to test the property
            //modelInstance.active shouldBe ("TODO")
        }

        // to test the property `hierarchy`
        should("test hierarchy") {
            // uncomment below to test the property
            //modelInstance.hierarchy shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `officeId`
        should("test officeId") {
            // uncomment below to test the property
            //modelInstance.officeId shouldBe ("TODO")
        }

        // to test the property `officeName`
        should("test officeName") {
            // uncomment below to test the property
            //modelInstance.officeName shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

    }
}
