/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetCurrenciesResponse
import org.openapitools.client.models.CurrencyData

class GetCurrenciesResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetCurrenciesResponse
        //val modelInstance = GetCurrenciesResponse()

        // to test the property `currencyOptions`
        should("test currencyOptions") {
            // uncomment below to test the property
            //modelInstance.currencyOptions shouldBe ("TODO")
        }

        // to test the property `selectedCurrencyOptions`
        should("test selectedCurrencyOptions") {
            // uncomment below to test the property
            //modelInstance.selectedCurrencyOptions shouldBe ("TODO")
        }

    }
}
