/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetFromAccountOptions
import org.openapitools.client.models.GetAccountOptions

class GetFromAccountOptionsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetFromAccountOptions
        //val modelInstance = GetFromAccountOptions()

        // to test the property `accountId`
        should("test accountId") {
            // uncomment below to test the property
            //modelInstance.accountId shouldBe ("TODO")
        }

        // to test the property `accountNo`
        should("test accountNo") {
            // uncomment below to test the property
            //modelInstance.accountNo shouldBe ("TODO")
        }

        // to test the property `accountType`
        should("test accountType") {
            // uncomment below to test the property
            //modelInstance.accountType shouldBe ("TODO")
        }

        // to test the property `clientId`
        should("test clientId") {
            // uncomment below to test the property
            //modelInstance.clientId shouldBe ("TODO")
        }

        // to test the property `clientName`
        should("test clientName") {
            // uncomment below to test the property
            //modelInstance.clientName shouldBe ("TODO")
        }

        // to test the property `officeId`
        should("test officeId") {
            // uncomment below to test the property
            //modelInstance.officeId shouldBe ("TODO")
        }

        // to test the property `officeName`
        should("test officeName") {
            // uncomment below to test the property
            //modelInstance.officeName shouldBe ("TODO")
        }

    }
}
