/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetFixedDepositProductsProductIdPenaltyToIncomeAccountMappings
import org.openapitools.client.models.GetFixedDepositProductsProductIdIncomeFromPenaltyAccount
import org.openapitools.client.models.GetFixedDepositProductsProductIdPenaltyToIncomeAccountMappingsCharge

class GetFixedDepositProductsProductIdPenaltyToIncomeAccountMappingsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetFixedDepositProductsProductIdPenaltyToIncomeAccountMappings
        //val modelInstance = GetFixedDepositProductsProductIdPenaltyToIncomeAccountMappings()

        // to test the property `charge`
        should("test charge") {
            // uncomment below to test the property
            //modelInstance.charge shouldBe ("TODO")
        }

        // to test the property `incomeAccount`
        should("test incomeAccount") {
            // uncomment below to test the property
            //modelInstance.incomeAccount shouldBe ("TODO")
        }

    }
}
