/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetFieldConfigurationEntityResponse

class GetFieldConfigurationEntityResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetFieldConfigurationEntityResponse
        //val modelInstance = GetFieldConfigurationEntityResponse()

        // to test the property `entity`
        should("test entity") {
            // uncomment below to test the property
            //modelInstance.entity shouldBe ("TODO")
        }

        // to test the property ``field``
        should("test `field`") {
            // uncomment below to test the property
            //modelInstance.`field` shouldBe ("TODO")
        }

        // to test the property `fieldConfigurationId`
        should("test fieldConfigurationId") {
            // uncomment below to test the property
            //modelInstance.fieldConfigurationId shouldBe ("TODO")
        }

        // to test the property `isEnabled`
        should("test isEnabled") {
            // uncomment below to test the property
            //modelInstance.isEnabled shouldBe ("TODO")
        }

        // to test the property `isMandatory`
        should("test isMandatory") {
            // uncomment below to test the property
            //modelInstance.isMandatory shouldBe ("TODO")
        }

        // to test the property `subentity`
        should("test subentity") {
            // uncomment below to test the property
            //modelInstance.subentity shouldBe ("TODO")
        }

        // to test the property `validationRegex`
        should("test validationRegex") {
            // uncomment below to test the property
            //modelInstance.validationRegex shouldBe ("TODO")
        }

    }
}
