/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetOfficesTemplateResponse
import org.openapitools.client.models.GetOfficesResponse

class GetOfficesTemplateResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetOfficesTemplateResponse
        //val modelInstance = GetOfficesTemplateResponse()

        // to test the property `allowedParents`
        should("test allowedParents") {
            // uncomment below to test the property
            //modelInstance.allowedParents shouldBe ("TODO")
        }

        // to test the property `openingDate`
        should("test openingDate") {
            // uncomment below to test the property
            //modelInstance.openingDate shouldBe ("TODO")
        }

    }
}
