/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetProductsMarketPrice

class GetProductsMarketPriceTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetProductsMarketPrice
        //val modelInstance = GetProductsMarketPrice()

        // to test the property `fromDate`
        should("test fromDate") {
            // uncomment below to test the property
            //modelInstance.fromDate shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `shareValue`
        should("test shareValue") {
            // uncomment below to test the property
            //modelInstance.shareValue shouldBe ("TODO")
        }

    }
}
