/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetRecurringDepositProductsProductIdActiveChart
import org.openapitools.client.models.GetRecurringDepositProductsProductIdChartSlabs
import org.openapitools.client.models.GetRecurringDepositProductsProductIdPeriodType

class GetRecurringDepositProductsProductIdActiveChartTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetRecurringDepositProductsProductIdActiveChart
        //val modelInstance = GetRecurringDepositProductsProductIdActiveChart()

        // to test the property `chartSlabs`
        should("test chartSlabs") {
            // uncomment below to test the property
            //modelInstance.chartSlabs shouldBe ("TODO")
        }

        // to test the property `fromDate`
        should("test fromDate") {
            // uncomment below to test the property
            //modelInstance.fromDate shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `periodTypes`
        should("test periodTypes") {
            // uncomment below to test the property
            //modelInstance.periodTypes shouldBe ("TODO")
        }

        // to test the property `savingsProductId`
        should("test savingsProductId") {
            // uncomment below to test the property
            //modelInstance.savingsProductId shouldBe ("TODO")
        }

        // to test the property `savingsProductName`
        should("test savingsProductName") {
            // uncomment below to test the property
            //modelInstance.savingsProductName shouldBe ("TODO")
        }

    }
}
