/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetSelfLoansLoanIdTransactionsType

class GetSelfLoansLoanIdTransactionsTypeTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetSelfLoansLoanIdTransactionsType
        //val modelInstance = GetSelfLoansLoanIdTransactionsType()

        // to test the property `code`
        should("test code") {
            // uncomment below to test the property
            //modelInstance.code shouldBe ("TODO")
        }

        // to test the property `contra`
        should("test contra") {
            // uncomment below to test the property
            //modelInstance.contra shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `disbursement`
        should("test disbursement") {
            // uncomment below to test the property
            //modelInstance.disbursement shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `recoveryRepayment`
        should("test recoveryRepayment") {
            // uncomment below to test the property
            //modelInstance.recoveryRepayment shouldBe ("TODO")
        }

        // to test the property `repayment`
        should("test repayment") {
            // uncomment below to test the property
            //modelInstance.repayment shouldBe ("TODO")
        }

        // to test the property `repaymentAtDisbursement`
        should("test repaymentAtDisbursement") {
            // uncomment below to test the property
            //modelInstance.repaymentAtDisbursement shouldBe ("TODO")
        }

        // to test the property `waiveCharges`
        should("test waiveCharges") {
            // uncomment below to test the property
            //modelInstance.waiveCharges shouldBe ("TODO")
        }

        // to test the property `waiveInterest`
        should("test waiveInterest") {
            // uncomment below to test the property
            //modelInstance.waiveInterest shouldBe ("TODO")
        }

        // to test the property `writeOff`
        should("test writeOff") {
            // uncomment below to test the property
            //modelInstance.writeOff shouldBe ("TODO")
        }

    }
}
