/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetSelfClientsPageItems
import org.openapitools.client.models.GetSelfClientsStatus

class GetSelfClientsPageItemsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetSelfClientsPageItems
        //val modelInstance = GetSelfClientsPageItems()

        // to test the property `accountNo`
        should("test accountNo") {
            // uncomment below to test the property
            //modelInstance.accountNo shouldBe ("TODO")
        }

        // to test the property `activationDate`
        should("test activationDate") {
            // uncomment below to test the property
            //modelInstance.activationDate shouldBe ("TODO")
        }

        // to test the property `active`
        should("test active") {
            // uncomment below to test the property
            //modelInstance.active shouldBe ("TODO")
        }

        // to test the property `displayName`
        should("test displayName") {
            // uncomment below to test the property
            //modelInstance.displayName shouldBe ("TODO")
        }

        // to test the property `fullname`
        should("test fullname") {
            // uncomment below to test the property
            //modelInstance.fullname shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `officeId`
        should("test officeId") {
            // uncomment below to test the property
            //modelInstance.officeId shouldBe ("TODO")
        }

        // to test the property `officeName`
        should("test officeName") {
            // uncomment below to test the property
            //modelInstance.officeName shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

    }
}
