/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.Image

class ImageTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Image
        //val modelInstance = Image()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `location`
        should("test location") {
            // uncomment below to test the property
            //modelInstance.location shouldBe ("TODO")
        }

        // to test the property `new`
        should("test new") {
            // uncomment below to test the property
            //modelInstance.new shouldBe ("TODO")
        }

        // to test the property `storageType`
        should("test storageType") {
            // uncomment below to test the property
            //modelInstance.storageType shouldBe ("TODO")
        }

    }
}
