/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.LoanProductFloatingRates
import org.openapitools.client.models.FloatingRate
import org.openapitools.client.models.LoanProduct

class LoanProductFloatingRatesTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LoanProductFloatingRates
        //val modelInstance = LoanProductFloatingRates()

        // to test the property `defaultDifferentialLendingRate`
        should("test defaultDifferentialLendingRate") {
            // uncomment below to test the property
            //modelInstance.defaultDifferentialLendingRate shouldBe ("TODO")
        }

        // to test the property `floatingInterestRateCalculationAllowed`
        should("test floatingInterestRateCalculationAllowed") {
            // uncomment below to test the property
            //modelInstance.floatingInterestRateCalculationAllowed shouldBe ("TODO")
        }

        // to test the property `floatingRate`
        should("test floatingRate") {
            // uncomment below to test the property
            //modelInstance.floatingRate shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `interestRateDifferential`
        should("test interestRateDifferential") {
            // uncomment below to test the property
            //modelInstance.interestRateDifferential shouldBe ("TODO")
        }

        // to test the property `loanProduct`
        should("test loanProduct") {
            // uncomment below to test the property
            //modelInstance.loanProduct shouldBe ("TODO")
        }

        // to test the property `maxDifferentialLendingRate`
        should("test maxDifferentialLendingRate") {
            // uncomment below to test the property
            //modelInstance.maxDifferentialLendingRate shouldBe ("TODO")
        }

        // to test the property `minDifferentialLendingRate`
        should("test minDifferentialLendingRate") {
            // uncomment below to test the property
            //modelInstance.minDifferentialLendingRate shouldBe ("TODO")
        }

        // to test the property `new`
        should("test new") {
            // uncomment below to test the property
            //modelInstance.new shouldBe ("TODO")
        }

    }
}
