/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.PostLoansLoanIdDisbursementData

class PostLoansLoanIdDisbursementDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PostLoansLoanIdDisbursementData
        //val modelInstance = PostLoansLoanIdDisbursementData()

        // to test the property `expectedDisbursementDate`
        should("test expectedDisbursementDate") {
            // uncomment below to test the property
            //modelInstance.expectedDisbursementDate shouldBe ("TODO")
        }

        // to test the property `principal`
        should("test principal") {
            // uncomment below to test the property
            //modelInstance.principal shouldBe ("TODO")
        }

    }
}
