/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.PostSavingsAccountsAccountIdRequest

class PostSavingsAccountsAccountIdRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PostSavingsAccountsAccountIdRequest
        //val modelInstance = PostSavingsAccountsAccountIdRequest()

        // to test the property `activatedOnDate`
        should("test activatedOnDate") {
            // uncomment below to test the property
            //modelInstance.activatedOnDate shouldBe ("TODO")
        }

        // to test the property `approvedOnDate`
        should("test approvedOnDate") {
            // uncomment below to test the property
            //modelInstance.approvedOnDate shouldBe ("TODO")
        }

        // to test the property `dateFormat`
        should("test dateFormat") {
            // uncomment below to test the property
            //modelInstance.dateFormat shouldBe ("TODO")
        }

        // to test the property `locale`
        should("test locale") {
            // uncomment below to test the property
            //modelInstance.locale shouldBe ("TODO")
        }

    }
}
