/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.PostStandingInstructionsRequest

class PostStandingInstructionsRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PostStandingInstructionsRequest
        //val modelInstance = PostStandingInstructionsRequest()

        // to test the property `amount`
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

        // to test the property `dateFormat`
        should("test dateFormat") {
            // uncomment below to test the property
            //modelInstance.dateFormat shouldBe ("TODO")
        }

        // to test the property `fromAccountId`
        should("test fromAccountId") {
            // uncomment below to test the property
            //modelInstance.fromAccountId shouldBe ("TODO")
        }

        // to test the property `fromAccountType`
        should("test fromAccountType") {
            // uncomment below to test the property
            //modelInstance.fromAccountType shouldBe ("TODO")
        }

        // to test the property `fromClientId`
        should("test fromClientId") {
            // uncomment below to test the property
            //modelInstance.fromClientId shouldBe ("TODO")
        }

        // to test the property `fromOfficeId`
        should("test fromOfficeId") {
            // uncomment below to test the property
            //modelInstance.fromOfficeId shouldBe ("TODO")
        }

        // to test the property `instructionType`
        should("test instructionType") {
            // uncomment below to test the property
            //modelInstance.instructionType shouldBe ("TODO")
        }

        // to test the property `locale` - en
        should("test locale") {
            // uncomment below to test the property
            //modelInstance.locale shouldBe ("TODO")
        }

        // to test the property `monthDayFormat`
        should("test monthDayFormat") {
            // uncomment below to test the property
            //modelInstance.monthDayFormat shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `priority`
        should("test priority") {
            // uncomment below to test the property
            //modelInstance.priority shouldBe ("TODO")
        }

        // to test the property `recurrenceFrequency`
        should("test recurrenceFrequency") {
            // uncomment below to test the property
            //modelInstance.recurrenceFrequency shouldBe ("TODO")
        }

        // to test the property `recurrenceInterval`
        should("test recurrenceInterval") {
            // uncomment below to test the property
            //modelInstance.recurrenceInterval shouldBe ("TODO")
        }

        // to test the property `recurrenceOnMonthDay`
        should("test recurrenceOnMonthDay") {
            // uncomment below to test the property
            //modelInstance.recurrenceOnMonthDay shouldBe ("TODO")
        }

        // to test the property `recurrenceType`
        should("test recurrenceType") {
            // uncomment below to test the property
            //modelInstance.recurrenceType shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `toAccountId`
        should("test toAccountId") {
            // uncomment below to test the property
            //modelInstance.toAccountId shouldBe ("TODO")
        }

        // to test the property `toAccountType`
        should("test toAccountType") {
            // uncomment below to test the property
            //modelInstance.toAccountType shouldBe ("TODO")
        }

        // to test the property `toClientId`
        should("test toClientId") {
            // uncomment below to test the property
            //modelInstance.toClientId shouldBe ("TODO")
        }

        // to test the property `toOfficeId`
        should("test toOfficeId") {
            // uncomment below to test the property
            //modelInstance.toOfficeId shouldBe ("TODO")
        }

        // to test the property `transferType`
        should("test transferType") {
            // uncomment below to test the property
            //modelInstance.transferType shouldBe ("TODO")
        }

        // to test the property `validFrom`
        should("test validFrom") {
            // uncomment below to test the property
            //modelInstance.validFrom shouldBe ("TODO")
        }

    }
}
