/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.PostInterestRateChartsChartIdChartSlabsRequest
import org.openapitools.client.models.PostInterestRateChartsChartIdChartSlabsIncentives

class PostInterestRateChartsChartIdChartSlabsRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PostInterestRateChartsChartIdChartSlabsRequest
        //val modelInstance = PostInterestRateChartsChartIdChartSlabsRequest()

        // to test the property `annualInterestRate`
        should("test annualInterestRate") {
            // uncomment below to test the property
            //modelInstance.annualInterestRate shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `fromPeriod`
        should("test fromPeriod") {
            // uncomment below to test the property
            //modelInstance.fromPeriod shouldBe ("TODO")
        }

        // to test the property `incentives`
        should("test incentives") {
            // uncomment below to test the property
            //modelInstance.incentives shouldBe ("TODO")
        }

        // to test the property `locale`
        should("test locale") {
            // uncomment below to test the property
            //modelInstance.locale shouldBe ("TODO")
        }

        // to test the property `periodType`
        should("test periodType") {
            // uncomment below to test the property
            //modelInstance.periodType shouldBe ("TODO")
        }

        // to test the property `toPeriod`
        should("test toPeriod") {
            // uncomment below to test the property
            //modelInstance.toPeriod shouldBe ("TODO")
        }

    }
}
