/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.PutClientClientIdAddressesRequest

class PutClientClientIdAddressesRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PutClientClientIdAddressesRequest
        //val modelInstance = PutClientClientIdAddressesRequest()

        // to test the property `addressId`
        should("test addressId") {
            // uncomment below to test the property
            //modelInstance.addressId shouldBe ("TODO")
        }

        // to test the property `street`
        should("test street") {
            // uncomment below to test the property
            //modelInstance.street shouldBe ("TODO")
        }

    }
}
