/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.PutGlobalConfigurationsResponsechangesSwagger

class PutGlobalConfigurationsResponsechangesSwaggerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PutGlobalConfigurationsResponsechangesSwagger
        //val modelInstance = PutGlobalConfigurationsResponsechangesSwagger()

        // to test the property `dateValue`
        should("test dateValue") {
            // uncomment below to test the property
            //modelInstance.dateValue shouldBe ("TODO")
        }

        // to test the property `enabled`
        should("test enabled") {
            // uncomment below to test the property
            //modelInstance.enabled shouldBe ("TODO")
        }

        // to test the property `stringValue`
        should("test stringValue") {
            // uncomment below to test the property
            //modelInstance.stringValue shouldBe ("TODO")
        }

        // to test the property ``value``
        should("test `value`") {
            // uncomment below to test the property
            //modelInstance.`value` shouldBe ("TODO")
        }

    }
}
