/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.PutOfficesOfficeIdResponse
import org.openapitools.client.models.PutOfficesOfficeIdResponseChanges

class PutOfficesOfficeIdResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PutOfficesOfficeIdResponse
        //val modelInstance = PutOfficesOfficeIdResponse()

        // to test the property `changes`
        should("test changes") {
            // uncomment below to test the property
            //modelInstance.changes shouldBe ("TODO")
        }

        // to test the property `officeId`
        should("test officeId") {
            // uncomment below to test the property
            //modelInstance.officeId shouldBe ("TODO")
        }

        // to test the property `resourceId`
        should("test resourceId") {
            // uncomment below to test the property
            //modelInstance.resourceId shouldBe ("TODO")
        }

    }
}
