/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.PutRecurringDepositProductsChanges

class PutRecurringDepositProductsChangesTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PutRecurringDepositProductsChanges
        //val modelInstance = PutRecurringDepositProductsChanges()

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `minDepositTerm`
        should("test minDepositTerm") {
            // uncomment below to test the property
            //modelInstance.minDepositTerm shouldBe ("TODO")
        }

    }
}
