/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.PutWorkingDaysRequest
import org.openapitools.client.models.EnumOptionData

class PutWorkingDaysRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PutWorkingDaysRequest
        //val modelInstance = PutWorkingDaysRequest()

        // to test the property `extendTermForDailyRepayments`
        should("test extendTermForDailyRepayments") {
            // uncomment below to test the property
            //modelInstance.extendTermForDailyRepayments shouldBe ("TODO")
        }

        // to test the property `locale`
        should("test locale") {
            // uncomment below to test the property
            //modelInstance.locale shouldBe ("TODO")
        }

        // to test the property `recurrence`
        should("test recurrence") {
            // uncomment below to test the property
            //modelInstance.recurrence shouldBe ("TODO")
        }

        // to test the property `repaymentRescheduleType`
        should("test repaymentRescheduleType") {
            // uncomment below to test the property
            //modelInstance.repaymentRescheduleType shouldBe ("TODO")
        }

    }
}
