/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ReportMailingJobTimelineData

class ReportMailingJobTimelineDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ReportMailingJobTimelineData
        //val modelInstance = ReportMailingJobTimelineData()

        // to test the property `createdByFirstname`
        should("test createdByFirstname") {
            // uncomment below to test the property
            //modelInstance.createdByFirstname shouldBe ("TODO")
        }

        // to test the property `createdByLastname`
        should("test createdByLastname") {
            // uncomment below to test the property
            //modelInstance.createdByLastname shouldBe ("TODO")
        }

        // to test the property `createdByUsername`
        should("test createdByUsername") {
            // uncomment below to test the property
            //modelInstance.createdByUsername shouldBe ("TODO")
        }

        // to test the property `createdOnDate`
        should("test createdOnDate") {
            // uncomment below to test the property
            //modelInstance.createdOnDate shouldBe ("TODO")
        }

        // to test the property `updatedByFirstname`
        should("test updatedByFirstname") {
            // uncomment below to test the property
            //modelInstance.updatedByFirstname shouldBe ("TODO")
        }

        // to test the property `updatedByLastname`
        should("test updatedByLastname") {
            // uncomment below to test the property
            //modelInstance.updatedByLastname shouldBe ("TODO")
        }

        // to test the property `updatedByUsername`
        should("test updatedByUsername") {
            // uncomment below to test the property
            //modelInstance.updatedByUsername shouldBe ("TODO")
        }

        // to test the property `updatedOnDate`
        should("test updatedOnDate") {
            // uncomment below to test the property
            //modelInstance.updatedOnDate shouldBe ("TODO")
        }

    }
}
