/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.AuditsApi
import org.openapitools.client.models.GetMakerCheckerResponse
import org.openapitools.client.models.GetMakerCheckersSearchTemplateResponse

class AuditsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AuditsApi
        //val apiInstance = AuditsApi()

        // to test retrieveAuditEntries
        should("test retrieveAuditEntries") {
            // uncomment below to test retrieveAuditEntries
            //val actionName : kotlin.String = actionName_example // kotlin.String | actionName
            //val entityName : kotlin.String = entityName_example // kotlin.String | entityName
            //val resourceId : kotlin.Long = 789 // kotlin.Long | resourceId
            //val makerId : kotlin.Long = 789 // kotlin.Long | makerId
            //val makerDateTimeFrom : kotlin.String = makerDateTimeFrom_example // kotlin.String | makerDateTimeFrom
            //val makerDateTimeTo : kotlin.String = makerDateTimeTo_example // kotlin.String | makerDateTimeTo
            //val checkerId : kotlin.Long = 789 // kotlin.Long | checkerId
            //val checkerDateTimeFrom : kotlin.String = checkerDateTimeFrom_example // kotlin.String | checkerDateTimeFrom
            //val checkerDateTimeTo : kotlin.String = checkerDateTimeTo_example // kotlin.String | checkerDateTimeTo
            //val processingResult : kotlin.Int = 56 // kotlin.Int | processingResult
            //val officeId : kotlin.Int = 56 // kotlin.Int | officeId
            //val groupId : kotlin.Int = 56 // kotlin.Int | groupId
            //val clientId : kotlin.Int = 56 // kotlin.Int | clientId
            //val loanid : kotlin.Int = 56 // kotlin.Int | loanid
            //val savingsAccountId : kotlin.Int = 56 // kotlin.Int | savingsAccountId
            //val paged : kotlin.Boolean = true // kotlin.Boolean | paged
            //val offset : kotlin.Int = 56 // kotlin.Int | offset
            //val limit : kotlin.Int = 56 // kotlin.Int | limit
            //val orderBy : kotlin.String = orderBy_example // kotlin.String | orderBy
            //val sortOrder : kotlin.String = sortOrder_example // kotlin.String | sortOrder
            //val result : kotlin.collections.List<GetMakerCheckerResponse> = apiInstance.retrieveAuditEntries(actionName, entityName, resourceId, makerId, makerDateTimeFrom, makerDateTimeTo, checkerId, checkerDateTimeFrom, checkerDateTimeTo, processingResult, officeId, groupId, clientId, loanid, savingsAccountId, paged, offset, limit, orderBy, sortOrder)
            //result shouldBe ("TODO")
        }

        // to test retrieveAuditEntry
        should("test retrieveAuditEntry") {
            // uncomment below to test retrieveAuditEntry
            //val auditId : kotlin.Long = 789 // kotlin.Long | auditId
            //val result : GetMakerCheckerResponse = apiInstance.retrieveAuditEntry(auditId)
            //result shouldBe ("TODO")
        }

        // to test retrieveAuditSearchTemplate
        should("test retrieveAuditSearchTemplate") {
            // uncomment below to test retrieveAuditSearchTemplate
            //val result : GetMakerCheckersSearchTemplateResponse = apiInstance.retrieveAuditSearchTemplate()
            //result shouldBe ("TODO")
        }

    }
}
