/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.PocketApi
import org.openapitools.client.models.GetAccountsLinkedToPocketResponse
import org.openapitools.client.models.PostLinkDelinkAccountsToFromPocketResponse

class PocketApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PocketApi
        //val apiInstance = PocketApi()

        // to test handleCommands8
        should("test handleCommands8") {
            // uncomment below to test handleCommands8
            //val command : kotlin.String = command_example // kotlin.String | command
            //val body : kotlin.String = body_example // kotlin.String | 
            //val result : PostLinkDelinkAccountsToFromPocketResponse = apiInstance.handleCommands8(command, body)
            //result shouldBe ("TODO")
        }

        // to test retrieveAll37
        should("test retrieveAll37") {
            // uncomment below to test retrieveAll37
            //val result : GetAccountsLinkedToPocketResponse = apiInstance.retrieveAll37()
            //result shouldBe ("TODO")
        }

    }
}
