/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.RecurringDepositAccountTransactionsApi
import org.openapitools.client.models.GetRecurringDepositAccountsRecurringDepositAccountIdTransactionsTemplateResponse
import org.openapitools.client.models.GetRecurringDepositAccountsRecurringDepositAccountIdTransactionsTransactionIdResponse
import org.openapitools.client.models.PostRecurringDepositAccountsRecurringDepositAccountIdTransactionsRequest
import org.openapitools.client.models.PostRecurringDepositAccountsRecurringDepositAccountIdTransactionsResponse
import org.openapitools.client.models.PostRecurringDepositAccountsRecurringDepositAccountIdTransactionsTransactionIdResponse

class RecurringDepositAccountTransactionsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RecurringDepositAccountTransactionsApi
        //val apiInstance = RecurringDepositAccountTransactionsApi()

        // to test handleTransactionCommands
        should("test handleTransactionCommands") {
            // uncomment below to test handleTransactionCommands
            //val recurringDepositAccountId : kotlin.Long = 789 // kotlin.Long | recurringDepositAccountId
            //val transactionId : kotlin.Long = 789 // kotlin.Long | transactionId
            //val postRecurringDepositAccountsRecurringDepositAccountIdTransactionsRequest : PostRecurringDepositAccountsRecurringDepositAccountIdTransactionsRequest =  // PostRecurringDepositAccountsRecurringDepositAccountIdTransactionsRequest | 
            //val command : kotlin.String = command_example // kotlin.String | command
            //val result : PostRecurringDepositAccountsRecurringDepositAccountIdTransactionsTransactionIdResponse = apiInstance.handleTransactionCommands(recurringDepositAccountId, transactionId, postRecurringDepositAccountsRecurringDepositAccountIdTransactionsRequest, command)
            //result shouldBe ("TODO")
        }

        // to test retrieveOne21
        should("test retrieveOne21") {
            // uncomment below to test retrieveOne21
            //val recurringDepositAccountId : kotlin.Long = 789 // kotlin.Long | recurringDepositAccountId
            //val transactionId : kotlin.Long = 789 // kotlin.Long | transactionId
            //val result : GetRecurringDepositAccountsRecurringDepositAccountIdTransactionsTransactionIdResponse = apiInstance.retrieveOne21(recurringDepositAccountId, transactionId)
            //result shouldBe ("TODO")
        }

        // to test retrieveTemplate16
        should("test retrieveTemplate16") {
            // uncomment below to test retrieveTemplate16
            //val recurringDepositAccountId : kotlin.Long = 789 // kotlin.Long | recurringDepositAccountId
            //val command : kotlin.String = command_example // kotlin.String | command
            //val result : GetRecurringDepositAccountsRecurringDepositAccountIdTransactionsTemplateResponse = apiInstance.retrieveTemplate16(recurringDepositAccountId, command)
            //result shouldBe ("TODO")
        }

        // to test transaction1
        should("test transaction1") {
            // uncomment below to test transaction1
            //val recurringDepositAccountId : kotlin.Long = 789 // kotlin.Long | recurringDepositAccountId
            //val postRecurringDepositAccountsRecurringDepositAccountIdTransactionsRequest : PostRecurringDepositAccountsRecurringDepositAccountIdTransactionsRequest =  // PostRecurringDepositAccountsRecurringDepositAccountIdTransactionsRequest | 
            //val command : kotlin.String = command_example // kotlin.String | command
            //val result : PostRecurringDepositAccountsRecurringDepositAccountIdTransactionsResponse = apiInstance.transaction1(recurringDepositAccountId, postRecurringDepositAccountsRecurringDepositAccountIdTransactionsRequest, command)
            //result shouldBe ("TODO")
        }

    }
}
