/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.SelfShareProductsApi

class SelfShareProductsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SelfShareProductsApi
        //val apiInstance = SelfShareProductsApi()

        // to test retrieveAllProducts1
        should("test retrieveAllProducts1") {
            // uncomment below to test retrieveAllProducts1
            //val clientId : kotlin.Long = 789 // kotlin.Long | 
            //val offset : kotlin.Int = 56 // kotlin.Int | 
            //val limit : kotlin.Int = 56 // kotlin.Int | 
            //val result : kotlin.String = apiInstance.retrieveAllProducts1(clientId, offset, limit)
            //result shouldBe ("TODO")
        }

        // to test retrieveProduct1
        should("test retrieveProduct1") {
            // uncomment below to test retrieveProduct1
            //val productId : kotlin.Long = 789 // kotlin.Long | 
            //val type : kotlin.String = type_example // kotlin.String | 
            //val clientId : kotlin.Long = 789 // kotlin.Long | 
            //val result : kotlin.String = apiInstance.retrieveProduct1(productId, type, clientId)
            //result shouldBe ("TODO")
        }

    }
}
