/*
 * Apache Fineract API Documentation
 * Apache Fineract is a secure, multi-tenanted microfinance platform. <br />              The goal of the Apache Fineract API is to empower developers to build apps on top of the Apache Fineract Platform. The reference app [  https://demo.openmf.org  ] (username: mifos, password: password) works on the same demo tenant as the interactive links in this documentation.              <br/>The API                 is organized around REST [ https://en.wikipedia.org/wiki/Representational_state_transfer ]               <br/> Find out more about Apache Fineract on [ https://demo.openmf.org/api-docs/apiLive.htm#top ]              <br/> You can Try The API From Your Browser itself at [ https://demo.openmf.org/api-docs/apiLive.htm#interact ]              <br/> The Generic Options are available at [ https://demo.openmf.org/api-docs/apiLive.htm#genopts ]              <br/> Find out more about Updating Dates and Numbers at [ https://demo.openmf.org/api-docs/apiLive.htm#dates_and_numbers ]              <br/> For the Authentication and the Basic of HTTP and HTTPS refer [ https://demo.openmf.org/api-docs/apiLive.htm#authentication_overview ]              <br/> Check about ERROR codes at [ https://demo.openmf.org/api-docs/apiLive.htm#errors ]               <br/> <br/> Please refer to the old documentation for any documentation queries [ https://demo.openmf.org/api-docs/apiLive.htm ]              <br/>             ______________________________________________________________________________________________________________________________
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.mifos.fineract.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * GetAccountsLinkedToPocketResponse
 */

public class GetAccountsLinkedToPocketResponse {
    @SerializedName("loanAccounts")
    private List<GetPocketLoanAccounts> loanAccounts = null;

    @SerializedName("savingAccounts")
    private List<GetPocketSavingAccounts> savingAccounts = null;

    @SerializedName("shareAccounts")
    private List<GetPocketShareAccounts> shareAccounts = null;

    public GetAccountsLinkedToPocketResponse loanAccounts(List<GetPocketLoanAccounts> loanAccounts) {
        this.loanAccounts = loanAccounts;
        return this;
    }

    public GetAccountsLinkedToPocketResponse addLoanAccountsItem(GetPocketLoanAccounts loanAccountsItem) {
        if (this.loanAccounts == null) {
            this.loanAccounts = new ArrayList<GetPocketLoanAccounts>();
        }
        this.loanAccounts.add(loanAccountsItem);
        return this;
    }

    /**
     * Get loanAccounts
     *
     * @return loanAccounts
     **/
    @ApiModelProperty(value = "")
    public List<GetPocketLoanAccounts> getLoanAccounts() {
        return loanAccounts;
    }

    public void setLoanAccounts(List<GetPocketLoanAccounts> loanAccounts) {
        this.loanAccounts = loanAccounts;
    }

    public GetAccountsLinkedToPocketResponse savingAccounts(List<GetPocketSavingAccounts> savingAccounts) {
        this.savingAccounts = savingAccounts;
        return this;
    }

    public GetAccountsLinkedToPocketResponse addSavingAccountsItem(GetPocketSavingAccounts savingAccountsItem) {
        if (this.savingAccounts == null) {
            this.savingAccounts = new ArrayList<GetPocketSavingAccounts>();
        }
        this.savingAccounts.add(savingAccountsItem);
        return this;
    }

    /**
     * Get savingAccounts
     *
     * @return savingAccounts
     **/
    @ApiModelProperty(value = "")
    public List<GetPocketSavingAccounts> getSavingAccounts() {
        return savingAccounts;
    }

    public void setSavingAccounts(List<GetPocketSavingAccounts> savingAccounts) {
        this.savingAccounts = savingAccounts;
    }

    public GetAccountsLinkedToPocketResponse shareAccounts(List<GetPocketShareAccounts> shareAccounts) {
        this.shareAccounts = shareAccounts;
        return this;
    }

    public GetAccountsLinkedToPocketResponse addShareAccountsItem(GetPocketShareAccounts shareAccountsItem) {
        if (this.shareAccounts == null) {
            this.shareAccounts = new ArrayList<GetPocketShareAccounts>();
        }
        this.shareAccounts.add(shareAccountsItem);
        return this;
    }

    /**
     * Get shareAccounts
     *
     * @return shareAccounts
     **/
    @ApiModelProperty(value = "")
    public List<GetPocketShareAccounts> getShareAccounts() {
        return shareAccounts;
    }

    public void setShareAccounts(List<GetPocketShareAccounts> shareAccounts) {
        this.shareAccounts = shareAccounts;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetAccountsLinkedToPocketResponse getAccountsLinkedToPocketResponse = (GetAccountsLinkedToPocketResponse) o;
        return Objects.equals(this.loanAccounts, getAccountsLinkedToPocketResponse.loanAccounts) &&
                Objects.equals(this.savingAccounts, getAccountsLinkedToPocketResponse.savingAccounts) &&
                Objects.equals(this.shareAccounts, getAccountsLinkedToPocketResponse.shareAccounts);
    }

    @Override
    public int hashCode() {
        return Objects.hash(loanAccounts, savingAccounts, shareAccounts);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class GetAccountsLinkedToPocketResponse {\n");

        sb.append("    loanAccounts: ").append(toIndentedString(loanAccounts)).append("\n");
        sb.append("    savingAccounts: ").append(toIndentedString(savingAccounts)).append("\n");
        sb.append("    shareAccounts: ").append(toIndentedString(shareAccounts)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

