/*
 * Apache Fineract API Documentation
 * Apache Fineract is a secure, multi-tenanted microfinance platform. <br/>              The goal of the Apache Fineract API is to empower developers to build apps on top of the Apache Fineract Platform. The reference app [  https://demo.openmf.org  ] (username: mifos, password: password) works on the same demo tenant as the interactive links in this documentation.              <br/>The API                 is organized around REST [ https://en.wikipedia.org/wiki/Representational_state_transfer ]               <br/> Find out more about Apache Fineract on [ https://demo.openmf.org/api-docs/apiLive.htm#top ]              <br/> You can Try The API From Your Browser itself at [ https://demo.openmf.org/api-docs/apiLive.htm#interact ]              <br/> The Generic Options are available at [ https://demo.openmf.org/api-docs/apiLive.htm#genopts ]              <br/> Find out more about Updating Dates and Numbers at [ https://demo.openmf.org/api-docs/apiLive.htm#dates_and_numbers ]              <br/> For the Authentication and the Basic of HTTP and HTTPS refer [ https://demo.openmf.org/api-docs/apiLive.htm#authentication_overview ]              <br/> Check about ERROR codes at [ https://demo.openmf.org/api-docs/apiLive.htm#errors ]               <br/> <br/> Please refer to the old documentation for any documentation queries [ https://demo.openmf.org/api-docs/apiLive.htm ]              <br/>             ______________________________________________________________________________________________________________________________
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.mifos.fineract.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * GetGlobalConfigurationsResponse
 */

public class GetGlobalConfigurationsResponse {
    @SerializedName("globalConfiguration")
    private List<GlobalConfigurationPropertyData> globalConfiguration = null;

    public GetGlobalConfigurationsResponse globalConfiguration(List<GlobalConfigurationPropertyData> globalConfiguration) {
        this.globalConfiguration = globalConfiguration;
        return this;
    }

    public GetGlobalConfigurationsResponse addGlobalConfigurationItem(GlobalConfigurationPropertyData globalConfigurationItem) {
        if (this.globalConfiguration == null) {
            this.globalConfiguration = new ArrayList<GlobalConfigurationPropertyData>();
        }
        this.globalConfiguration.add(globalConfigurationItem);
        return this;
    }

    /**
     * Get globalConfiguration
     *
     * @return globalConfiguration
     **/
    @ApiModelProperty(value = "")
    public List<GlobalConfigurationPropertyData> getGlobalConfiguration() {
        return globalConfiguration;
    }

    public void setGlobalConfiguration(List<GlobalConfigurationPropertyData> globalConfiguration) {
        this.globalConfiguration = globalConfiguration;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetGlobalConfigurationsResponse getGlobalConfigurationsResponse = (GetGlobalConfigurationsResponse) o;
        return Objects.equals(this.globalConfiguration, getGlobalConfigurationsResponse.globalConfiguration);
    }

    @Override
    public int hashCode() {
        return Objects.hash(globalConfiguration);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class GetGlobalConfigurationsResponse {\n");

        sb.append("    globalConfiguration: ").append(toIndentedString(globalConfiguration)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

