/*
 * Apache Fineract API Documentation
 * Apache Fineract is a secure, multi-tenanted microfinance platform. <br />              The goal of the Apache Fineract API is to empower developers to build apps on top of the Apache Fineract Platform. The reference app [  https://demo.openmf.org  ] (username: mifos, password: password) works on the same demo tenant as the interactive links in this documentation.              <br/>The API                 is organized around REST [ https://en.wikipedia.org/wiki/Representational_state_transfer ]               <br/> Find out more about Apache Fineract on [ https://demo.openmf.org/api-docs/apiLive.htm#top ]              <br/> You can Try The API From Your Browser itself at [ https://demo.openmf.org/api-docs/apiLive.htm#interact ]              <br/> The Generic Options are available at [ https://demo.openmf.org/api-docs/apiLive.htm#genopts ]              <br/> Find out more about Updating Dates and Numbers at [ https://demo.openmf.org/api-docs/apiLive.htm#dates_and_numbers ]              <br/> For the Authentication and the Basic of HTTP and HTTPS refer [ https://demo.openmf.org/api-docs/apiLive.htm#authentication_overview ]              <br/> Check about ERROR codes at [ https://demo.openmf.org/api-docs/apiLive.htm#errors ]               <br/> <br/> Please refer to the old documentation for any documentation queries [ https://demo.openmf.org/api-docs/apiLive.htm ]              <br/>             ______________________________________________________________________________________________________________________________
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.mifos.fineract.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * GetGroupsTemplateResponse
 */

public class GetGroupsTemplateResponse {
    @SerializedName("officeId")
    private Integer officeId = null;

    @SerializedName("officeOptions")
    private List<GetGroupsTemplateOfficeOptions> officeOptions = null;

    @SerializedName("staffOptions")
    private List<GetGroupsTemplateStaffOptions> staffOptions = null;

    @SerializedName("clientOptions")
    private List<GetGroupsTemplateClientOptions> clientOptions = null;

    @SerializedName("datatables")
    private List<GetGroupsTemplateDatatables> datatables = null;

    public GetGroupsTemplateResponse officeId(Integer officeId) {
        this.officeId = officeId;
        return this;
    }

    /**
     * Get officeId
     *
     * @return officeId
     **/
    @ApiModelProperty(example = "1", value = "")
    public Integer getOfficeId() {
        return officeId;
    }

    public void setOfficeId(Integer officeId) {
        this.officeId = officeId;
    }

    public GetGroupsTemplateResponse officeOptions(List<GetGroupsTemplateOfficeOptions> officeOptions) {
        this.officeOptions = officeOptions;
        return this;
    }

    public GetGroupsTemplateResponse addOfficeOptionsItem(GetGroupsTemplateOfficeOptions officeOptionsItem) {
        if (this.officeOptions == null) {
            this.officeOptions = new ArrayList<GetGroupsTemplateOfficeOptions>();
        }
        this.officeOptions.add(officeOptionsItem);
        return this;
    }

    /**
     * Get officeOptions
     *
     * @return officeOptions
     **/
    @ApiModelProperty(value = "")
    public List<GetGroupsTemplateOfficeOptions> getOfficeOptions() {
        return officeOptions;
    }

    public void setOfficeOptions(List<GetGroupsTemplateOfficeOptions> officeOptions) {
        this.officeOptions = officeOptions;
    }

    public GetGroupsTemplateResponse staffOptions(List<GetGroupsTemplateStaffOptions> staffOptions) {
        this.staffOptions = staffOptions;
        return this;
    }

    public GetGroupsTemplateResponse addStaffOptionsItem(GetGroupsTemplateStaffOptions staffOptionsItem) {
        if (this.staffOptions == null) {
            this.staffOptions = new ArrayList<GetGroupsTemplateStaffOptions>();
        }
        this.staffOptions.add(staffOptionsItem);
        return this;
    }

    /**
     * Get staffOptions
     *
     * @return staffOptions
     **/
    @ApiModelProperty(value = "")
    public List<GetGroupsTemplateStaffOptions> getStaffOptions() {
        return staffOptions;
    }

    public void setStaffOptions(List<GetGroupsTemplateStaffOptions> staffOptions) {
        this.staffOptions = staffOptions;
    }

    public GetGroupsTemplateResponse clientOptions(List<GetGroupsTemplateClientOptions> clientOptions) {
        this.clientOptions = clientOptions;
        return this;
    }

    public GetGroupsTemplateResponse addClientOptionsItem(GetGroupsTemplateClientOptions clientOptionsItem) {
        if (this.clientOptions == null) {
            this.clientOptions = new ArrayList<GetGroupsTemplateClientOptions>();
        }
        this.clientOptions.add(clientOptionsItem);
        return this;
    }

    /**
     * Get clientOptions
     *
     * @return clientOptions
     **/
    @ApiModelProperty(value = "")
    public List<GetGroupsTemplateClientOptions> getClientOptions() {
        return clientOptions;
    }

    public void setClientOptions(List<GetGroupsTemplateClientOptions> clientOptions) {
        this.clientOptions = clientOptions;
    }

    public GetGroupsTemplateResponse datatables(List<GetGroupsTemplateDatatables> datatables) {
        this.datatables = datatables;
        return this;
    }

    public GetGroupsTemplateResponse addDatatablesItem(GetGroupsTemplateDatatables datatablesItem) {
        if (this.datatables == null) {
            this.datatables = new ArrayList<GetGroupsTemplateDatatables>();
        }
        this.datatables.add(datatablesItem);
        return this;
    }

    /**
     * Get datatables
     *
     * @return datatables
     **/
    @ApiModelProperty(value = "")
    public List<GetGroupsTemplateDatatables> getDatatables() {
        return datatables;
    }

    public void setDatatables(List<GetGroupsTemplateDatatables> datatables) {
        this.datatables = datatables;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetGroupsTemplateResponse getGroupsTemplateResponse = (GetGroupsTemplateResponse) o;
        return Objects.equals(this.officeId, getGroupsTemplateResponse.officeId) &&
                Objects.equals(this.officeOptions, getGroupsTemplateResponse.officeOptions) &&
                Objects.equals(this.staffOptions, getGroupsTemplateResponse.staffOptions) &&
                Objects.equals(this.clientOptions, getGroupsTemplateResponse.clientOptions) &&
                Objects.equals(this.datatables, getGroupsTemplateResponse.datatables);
    }

    @Override
    public int hashCode() {
        return Objects.hash(officeId, officeOptions, staffOptions, clientOptions, datatables);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class GetGroupsTemplateResponse {\n");

        sb.append("    officeId: ").append(toIndentedString(officeId)).append("\n");
        sb.append("    officeOptions: ").append(toIndentedString(officeOptions)).append("\n");
        sb.append("    staffOptions: ").append(toIndentedString(staffOptions)).append("\n");
        sb.append("    clientOptions: ").append(toIndentedString(clientOptions)).append("\n");
        sb.append("    datatables: ").append(toIndentedString(datatables)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

