/*
 * Apache Fineract API Documentation
 * Apache Fineract is a secure, multi-tenanted microfinance platform. <br/>              The goal of the Apache Fineract API is to empower developers to build apps on top of the Apache Fineract Platform. The reference app [  https://demo.openmf.org  ] (username: mifos, password: password) works on the same demo tenant as the interactive links in this documentation.              <br/>The API                 is organized around REST [ https://en.wikipedia.org/wiki/Representational_state_transfer ]               <br/> Find out more about Apache Fineract on [ https://demo.openmf.org/api-docs/apiLive.htm#top ]              <br/> You can Try The API From Your Browser itself at [ https://demo.openmf.org/api-docs/apiLive.htm#interact ]              <br/> The Generic Options are available at [ https://demo.openmf.org/api-docs/apiLive.htm#genopts ]              <br/> Find out more about Updating Dates and Numbers at [ https://demo.openmf.org/api-docs/apiLive.htm#dates_and_numbers ]              <br/> For the Authentication and the Basic of HTTP and HTTPS refer [ https://demo.openmf.org/api-docs/apiLive.htm#authentication_overview ]              <br/> Check about ERROR codes at [ https://demo.openmf.org/api-docs/apiLive.htm#errors ]               <br/> <br/> Please refer to the old documentation for any documentation queries [ https://demo.openmf.org/api-docs/apiLive.htm ]              <br/>             ______________________________________________________________________________________________________________________________
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.mifos.fineract.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * GetLoanProductsInterestRecalculationData
 */

public class GetLoanProductsInterestRecalculationData {
    @SerializedName("id")
    private Integer id = null;

    @SerializedName("productId")
    private Integer productId = null;

    @SerializedName("interestRecalculationCompoundingType")
    private GetLoanProductsInterestRecalculationCompoundingType interestRecalculationCompoundingType = null;

    @SerializedName("interestRecalculationCompoundingFrequencyType")
    private GetLoanProductsInterestRecalculationCompoundingFrequencyType interestRecalculationCompoundingFrequencyType = null;

    @SerializedName("rescheduleStrategyType")
    private GetLoanProductsRescheduleStrategyType rescheduleStrategyType = null;

    @SerializedName("recalculationRestFrequencyType")
    private GetLoanProductsInterestRecalculationCompoundingFrequencyType recalculationRestFrequencyType = null;

    @SerializedName("preClosureInterestCalculationStrategy")
    private GetLoanProductsPreClosureInterestCalculationStrategy preClosureInterestCalculationStrategy = null;

    @SerializedName("isArrearsBasedOnOriginalSchedule")
    private Boolean isArrearsBasedOnOriginalSchedule = null;

    public GetLoanProductsInterestRecalculationData id(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/
    @ApiModelProperty(example = "3", value = "")
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public GetLoanProductsInterestRecalculationData productId(Integer productId) {
        this.productId = productId;
        return this;
    }

    /**
     * Get productId
     *
     * @return productId
     **/
    @ApiModelProperty(example = "1", value = "")
    public Integer getProductId() {
        return productId;
    }

    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    public GetLoanProductsInterestRecalculationData interestRecalculationCompoundingType(GetLoanProductsInterestRecalculationCompoundingType interestRecalculationCompoundingType) {
        this.interestRecalculationCompoundingType = interestRecalculationCompoundingType;
        return this;
    }

    /**
     * Get interestRecalculationCompoundingType
     *
     * @return interestRecalculationCompoundingType
     **/
    @ApiModelProperty(value = "")
    public GetLoanProductsInterestRecalculationCompoundingType getInterestRecalculationCompoundingType() {
        return interestRecalculationCompoundingType;
    }

    public void setInterestRecalculationCompoundingType(GetLoanProductsInterestRecalculationCompoundingType interestRecalculationCompoundingType) {
        this.interestRecalculationCompoundingType = interestRecalculationCompoundingType;
    }

    public GetLoanProductsInterestRecalculationData interestRecalculationCompoundingFrequencyType(GetLoanProductsInterestRecalculationCompoundingFrequencyType interestRecalculationCompoundingFrequencyType) {
        this.interestRecalculationCompoundingFrequencyType = interestRecalculationCompoundingFrequencyType;
        return this;
    }

    /**
     * Get interestRecalculationCompoundingFrequencyType
     *
     * @return interestRecalculationCompoundingFrequencyType
     **/
    @ApiModelProperty(value = "")
    public GetLoanProductsInterestRecalculationCompoundingFrequencyType getInterestRecalculationCompoundingFrequencyType() {
        return interestRecalculationCompoundingFrequencyType;
    }

    public void setInterestRecalculationCompoundingFrequencyType(GetLoanProductsInterestRecalculationCompoundingFrequencyType interestRecalculationCompoundingFrequencyType) {
        this.interestRecalculationCompoundingFrequencyType = interestRecalculationCompoundingFrequencyType;
    }

    public GetLoanProductsInterestRecalculationData rescheduleStrategyType(GetLoanProductsRescheduleStrategyType rescheduleStrategyType) {
        this.rescheduleStrategyType = rescheduleStrategyType;
        return this;
    }

    /**
     * Get rescheduleStrategyType
     *
     * @return rescheduleStrategyType
     **/
    @ApiModelProperty(value = "")
    public GetLoanProductsRescheduleStrategyType getRescheduleStrategyType() {
        return rescheduleStrategyType;
    }

    public void setRescheduleStrategyType(GetLoanProductsRescheduleStrategyType rescheduleStrategyType) {
        this.rescheduleStrategyType = rescheduleStrategyType;
    }

    public GetLoanProductsInterestRecalculationData recalculationRestFrequencyType(GetLoanProductsInterestRecalculationCompoundingFrequencyType recalculationRestFrequencyType) {
        this.recalculationRestFrequencyType = recalculationRestFrequencyType;
        return this;
    }

    /**
     * Get recalculationRestFrequencyType
     *
     * @return recalculationRestFrequencyType
     **/
    @ApiModelProperty(value = "")
    public GetLoanProductsInterestRecalculationCompoundingFrequencyType getRecalculationRestFrequencyType() {
        return recalculationRestFrequencyType;
    }

    public void setRecalculationRestFrequencyType(GetLoanProductsInterestRecalculationCompoundingFrequencyType recalculationRestFrequencyType) {
        this.recalculationRestFrequencyType = recalculationRestFrequencyType;
    }

    public GetLoanProductsInterestRecalculationData preClosureInterestCalculationStrategy(GetLoanProductsPreClosureInterestCalculationStrategy preClosureInterestCalculationStrategy) {
        this.preClosureInterestCalculationStrategy = preClosureInterestCalculationStrategy;
        return this;
    }

    /**
     * Get preClosureInterestCalculationStrategy
     *
     * @return preClosureInterestCalculationStrategy
     **/
    @ApiModelProperty(value = "")
    public GetLoanProductsPreClosureInterestCalculationStrategy getPreClosureInterestCalculationStrategy() {
        return preClosureInterestCalculationStrategy;
    }

    public void setPreClosureInterestCalculationStrategy(GetLoanProductsPreClosureInterestCalculationStrategy preClosureInterestCalculationStrategy) {
        this.preClosureInterestCalculationStrategy = preClosureInterestCalculationStrategy;
    }

    public GetLoanProductsInterestRecalculationData isArrearsBasedOnOriginalSchedule(Boolean isArrearsBasedOnOriginalSchedule) {
        this.isArrearsBasedOnOriginalSchedule = isArrearsBasedOnOriginalSchedule;
        return this;
    }

    /**
     * Get isArrearsBasedOnOriginalSchedule
     *
     * @return isArrearsBasedOnOriginalSchedule
     **/
    @ApiModelProperty(example = "true", value = "")
    public Boolean isIsArrearsBasedOnOriginalSchedule() {
        return isArrearsBasedOnOriginalSchedule;
    }

    public void setIsArrearsBasedOnOriginalSchedule(Boolean isArrearsBasedOnOriginalSchedule) {
        this.isArrearsBasedOnOriginalSchedule = isArrearsBasedOnOriginalSchedule;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetLoanProductsInterestRecalculationData getLoanProductsInterestRecalculationData = (GetLoanProductsInterestRecalculationData) o;
        return Objects.equals(this.id, getLoanProductsInterestRecalculationData.id) &&
                Objects.equals(this.productId, getLoanProductsInterestRecalculationData.productId) &&
                Objects.equals(this.interestRecalculationCompoundingType, getLoanProductsInterestRecalculationData.interestRecalculationCompoundingType) &&
                Objects.equals(this.interestRecalculationCompoundingFrequencyType, getLoanProductsInterestRecalculationData.interestRecalculationCompoundingFrequencyType) &&
                Objects.equals(this.rescheduleStrategyType, getLoanProductsInterestRecalculationData.rescheduleStrategyType) &&
                Objects.equals(this.recalculationRestFrequencyType, getLoanProductsInterestRecalculationData.recalculationRestFrequencyType) &&
                Objects.equals(this.preClosureInterestCalculationStrategy, getLoanProductsInterestRecalculationData.preClosureInterestCalculationStrategy) &&
                Objects.equals(this.isArrearsBasedOnOriginalSchedule, getLoanProductsInterestRecalculationData.isArrearsBasedOnOriginalSchedule);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, productId, interestRecalculationCompoundingType, interestRecalculationCompoundingFrequencyType, rescheduleStrategyType, recalculationRestFrequencyType, preClosureInterestCalculationStrategy, isArrearsBasedOnOriginalSchedule);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class GetLoanProductsInterestRecalculationData {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
        sb.append("    interestRecalculationCompoundingType: ").append(toIndentedString(interestRecalculationCompoundingType)).append("\n");
        sb.append("    interestRecalculationCompoundingFrequencyType: ").append(toIndentedString(interestRecalculationCompoundingFrequencyType)).append("\n");
        sb.append("    rescheduleStrategyType: ").append(toIndentedString(rescheduleStrategyType)).append("\n");
        sb.append("    recalculationRestFrequencyType: ").append(toIndentedString(recalculationRestFrequencyType)).append("\n");
        sb.append("    preClosureInterestCalculationStrategy: ").append(toIndentedString(preClosureInterestCalculationStrategy)).append("\n");
        sb.append("    isArrearsBasedOnOriginalSchedule: ").append(toIndentedString(isArrearsBasedOnOriginalSchedule)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

