/*
 * Apache Fineract API Documentation
 * Apache Fineract is a secure, multi-tenanted microfinance platform. <br/>              The goal of the Apache Fineract API is to empower developers to build apps on top of the Apache Fineract Platform. The reference app [  https://demo.openmf.org  ] (username: mifos, password: password) works on the same demo tenant as the interactive links in this documentation.              <br/>The API                 is organized around REST [ https://en.wikipedia.org/wiki/Representational_state_transfer ]               <br/> Find out more about Apache Fineract on [ https://demo.openmf.org/api-docs/apiLive.htm#top ]              <br/> You can Try The API From Your Browser itself at [ https://demo.openmf.org/api-docs/apiLive.htm#interact ]              <br/> The Generic Options are available at [ https://demo.openmf.org/api-docs/apiLive.htm#genopts ]              <br/> Find out more about Updating Dates and Numbers at [ https://demo.openmf.org/api-docs/apiLive.htm#dates_and_numbers ]              <br/> For the Authentication and the Basic of HTTP and HTTPS refer [ https://demo.openmf.org/api-docs/apiLive.htm#authentication_overview ]              <br/> Check about ERROR codes at [ https://demo.openmf.org/api-docs/apiLive.htm#errors ]               <br/> <br/> Please refer to the old documentation for any documentation queries [ https://demo.openmf.org/api-docs/apiLive.htm ]              <br/>             ______________________________________________________________________________________________________________________________
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.mifos.fineract.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * GetSelfClientsLoanAccounts
 */

public class GetSelfClientsLoanAccounts {
    @SerializedName("id")
    private Integer id = null;

    @SerializedName("accountNo")
    private Long accountNo = null;

    @SerializedName("externalId")
    private Integer externalId = null;

    @SerializedName("productId")
    private Integer productId = null;

    @SerializedName("productName")
    private String productName = null;

    @SerializedName("status")
    private GetSelfClientsLoanAccountsStatus status = null;

    @SerializedName("loanType")
    private GetSelfClientsLoanAccountsType loanType = null;

    @SerializedName("loanCycle")
    private Integer loanCycle = null;

    public GetSelfClientsLoanAccounts id(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/
    @ApiModelProperty(example = "1", value = "")
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public GetSelfClientsLoanAccounts accountNo(Long accountNo) {
        this.accountNo = accountNo;
        return this;
    }

    /**
     * Get accountNo
     *
     * @return accountNo
     **/
    @ApiModelProperty(example = "1", value = "")
    public Long getAccountNo() {
        return accountNo;
    }

    public void setAccountNo(Long accountNo) {
        this.accountNo = accountNo;
    }

    public GetSelfClientsLoanAccounts externalId(Integer externalId) {
        this.externalId = externalId;
        return this;
    }

    /**
     * Get externalId
     *
     * @return externalId
     **/
    @ApiModelProperty(example = "456", value = "")
    public Integer getExternalId() {
        return externalId;
    }

    public void setExternalId(Integer externalId) {
        this.externalId = externalId;
    }

    public GetSelfClientsLoanAccounts productId(Integer productId) {
        this.productId = productId;
        return this;
    }

    /**
     * Get productId
     *
     * @return productId
     **/
    @ApiModelProperty(example = "1", value = "")
    public Integer getProductId() {
        return productId;
    }

    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    public GetSelfClientsLoanAccounts productName(String productName) {
        this.productName = productName;
        return this;
    }

    /**
     * Get productName
     *
     * @return productName
     **/
    @ApiModelProperty(example = "TestOne", value = "")
    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public GetSelfClientsLoanAccounts status(GetSelfClientsLoanAccountsStatus status) {
        this.status = status;
        return this;
    }

    /**
     * Get status
     *
     * @return status
     **/
    @ApiModelProperty(value = "")
    public GetSelfClientsLoanAccountsStatus getStatus() {
        return status;
    }

    public void setStatus(GetSelfClientsLoanAccountsStatus status) {
        this.status = status;
    }

    public GetSelfClientsLoanAccounts loanType(GetSelfClientsLoanAccountsType loanType) {
        this.loanType = loanType;
        return this;
    }

    /**
     * Get loanType
     *
     * @return loanType
     **/
    @ApiModelProperty(value = "")
    public GetSelfClientsLoanAccountsType getLoanType() {
        return loanType;
    }

    public void setLoanType(GetSelfClientsLoanAccountsType loanType) {
        this.loanType = loanType;
    }

    public GetSelfClientsLoanAccounts loanCycle(Integer loanCycle) {
        this.loanCycle = loanCycle;
        return this;
    }

    /**
     * Get loanCycle
     *
     * @return loanCycle
     **/
    @ApiModelProperty(example = "1", value = "")
    public Integer getLoanCycle() {
        return loanCycle;
    }

    public void setLoanCycle(Integer loanCycle) {
        this.loanCycle = loanCycle;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetSelfClientsLoanAccounts getSelfClientsLoanAccounts = (GetSelfClientsLoanAccounts) o;
        return Objects.equals(this.id, getSelfClientsLoanAccounts.id) &&
                Objects.equals(this.accountNo, getSelfClientsLoanAccounts.accountNo) &&
                Objects.equals(this.externalId, getSelfClientsLoanAccounts.externalId) &&
                Objects.equals(this.productId, getSelfClientsLoanAccounts.productId) &&
                Objects.equals(this.productName, getSelfClientsLoanAccounts.productName) &&
                Objects.equals(this.status, getSelfClientsLoanAccounts.status) &&
                Objects.equals(this.loanType, getSelfClientsLoanAccounts.loanType) &&
                Objects.equals(this.loanCycle, getSelfClientsLoanAccounts.loanCycle);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, accountNo, externalId, productId, productName, status, loanType, loanCycle);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class GetSelfClientsLoanAccounts {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    accountNo: ").append(toIndentedString(accountNo)).append("\n");
        sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
        sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
        sb.append("    productName: ").append(toIndentedString(productName)).append("\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("    loanType: ").append(toIndentedString(loanType)).append("\n");
        sb.append("    loanCycle: ").append(toIndentedString(loanCycle)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

