/*
 * Apache Fineract API Documentation
 * Apache Fineract is a secure, multi-tenanted microfinance platform. <br/>              The goal of the Apache Fineract API is to empower developers to build apps on top of the Apache Fineract Platform. The reference app [  https://demo.openmf.org  ] (username: mifos, password: password) works on the same demo tenant as the interactive links in this documentation.              <br/>The API                 is organized around REST [ https://en.wikipedia.org/wiki/Representational_state_transfer ]               <br/> Find out more about Apache Fineract on [ https://demo.openmf.org/api-docs/apiLive.htm#top ]              <br/> You can Try The API From Your Browser itself at [ https://demo.openmf.org/api-docs/apiLive.htm#interact ]              <br/> The Generic Options are available at [ https://demo.openmf.org/api-docs/apiLive.htm#genopts ]              <br/> Find out more about Updating Dates and Numbers at [ https://demo.openmf.org/api-docs/apiLive.htm#dates_and_numbers ]              <br/> For the Authentication and the Basic of HTTP and HTTPS refer [ https://demo.openmf.org/api-docs/apiLive.htm#authentication_overview ]              <br/> Check about ERROR codes at [ https://demo.openmf.org/api-docs/apiLive.htm#errors ]               <br/> <br/> Please refer to the old documentation for any documentation queries [ https://demo.openmf.org/api-docs/apiLive.htm ]              <br/>             ______________________________________________________________________________________________________________________________
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.mifos.fineract.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * PostCollectionSheetBulkRepaymentTransactions
 */

public class PostCollectionSheetBulkRepaymentTransactions {
    @SerializedName("loanId")
    private Integer loanId = null;

    @SerializedName("transactionAmount")
    private Double transactionAmount = null;

    @SerializedName("paymentTypeId")
    private Integer paymentTypeId = null;

    @SerializedName("receiptNumber")
    private Long receiptNumber = null;

    public PostCollectionSheetBulkRepaymentTransactions loanId(Integer loanId) {
        this.loanId = loanId;
        return this;
    }

    /**
     * Get loanId
     *
     * @return loanId
     **/
    @ApiModelProperty(example = "10", value = "")
    public Integer getLoanId() {
        return loanId;
    }

    public void setLoanId(Integer loanId) {
        this.loanId = loanId;
    }

    public PostCollectionSheetBulkRepaymentTransactions transactionAmount(Double transactionAmount) {
        this.transactionAmount = transactionAmount;
        return this;
    }

    /**
     * Get transactionAmount
     *
     * @return transactionAmount
     **/
    @ApiModelProperty(example = "1221.36", value = "")
    public Double getTransactionAmount() {
        return transactionAmount;
    }

    public void setTransactionAmount(Double transactionAmount) {
        this.transactionAmount = transactionAmount;
    }

    public PostCollectionSheetBulkRepaymentTransactions paymentTypeId(Integer paymentTypeId) {
        this.paymentTypeId = paymentTypeId;
        return this;
    }

    /**
     * Get paymentTypeId
     *
     * @return paymentTypeId
     **/
    @ApiModelProperty(example = "19", value = "")
    public Integer getPaymentTypeId() {
        return paymentTypeId;
    }

    public void setPaymentTypeId(Integer paymentTypeId) {
        this.paymentTypeId = paymentTypeId;
    }

    public PostCollectionSheetBulkRepaymentTransactions receiptNumber(Long receiptNumber) {
        this.receiptNumber = receiptNumber;
        return this;
    }

    /**
     * Get receiptNumber
     *
     * @return receiptNumber
     **/
    @ApiModelProperty(example = "1245356", value = "")
    public Long getReceiptNumber() {
        return receiptNumber;
    }

    public void setReceiptNumber(Long receiptNumber) {
        this.receiptNumber = receiptNumber;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PostCollectionSheetBulkRepaymentTransactions postCollectionSheetBulkRepaymentTransactions = (PostCollectionSheetBulkRepaymentTransactions) o;
        return Objects.equals(this.loanId, postCollectionSheetBulkRepaymentTransactions.loanId) &&
                Objects.equals(this.transactionAmount, postCollectionSheetBulkRepaymentTransactions.transactionAmount) &&
                Objects.equals(this.paymentTypeId, postCollectionSheetBulkRepaymentTransactions.paymentTypeId) &&
                Objects.equals(this.receiptNumber, postCollectionSheetBulkRepaymentTransactions.receiptNumber);
    }

    @Override
    public int hashCode() {
        return Objects.hash(loanId, transactionAmount, paymentTypeId, receiptNumber);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PostCollectionSheetBulkRepaymentTransactions {\n");

        sb.append("    loanId: ").append(toIndentedString(loanId)).append("\n");
        sb.append("    transactionAmount: ").append(toIndentedString(transactionAmount)).append("\n");
        sb.append("    paymentTypeId: ").append(toIndentedString(paymentTypeId)).append("\n");
        sb.append("    receiptNumber: ").append(toIndentedString(receiptNumber)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

