/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param creationDate 
 * @param fileName 
 * @param modificationDate 
 * @param name 
 * @param parameters 
 * @param readDate 
 * @param propertySize 
 * @param type 
 */


data class FormDataContentDisposition (

    @Json(name = "creationDate")
    val creationDate: java.time.OffsetDateTime? = null,

    @Json(name = "fileName")
    val fileName: kotlin.String? = null,

    @Json(name = "modificationDate")
    val modificationDate: java.time.OffsetDateTime? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "parameters")
    val parameters: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @Json(name = "readDate")
    val readDate: java.time.OffsetDateTime? = null,

    @Json(name = "size")
    val propertySize: kotlin.Long? = null,

    @Json(name = "type")
    val type: kotlin.String? = null

) {


}

