/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.GetObligeeData

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * GetClientObligeeDetailsResponse
 *
 * @param obligees 
 */


data class GetClientObligeeDetailsResponse (

    @Json(name = "obligees")
    val obligees: kotlin.collections.Set<GetObligeeData>? = null

) {


}

