/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CurrencyData

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * GetCurrenciesResponse
 *
 * @param currencyOptions 
 * @param selectedCurrencyOptions 
 */


data class GetCurrenciesResponse (

    @Json(name = "currencyOptions")
    val currencyOptions: kotlin.collections.List<CurrencyData>? = null,

    @Json(name = "selectedCurrencyOptions")
    val selectedCurrencyOptions: kotlin.collections.List<CurrencyData>? = null

) {


}

