/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.GetFixedDepositProductsAccountingRule
import org.openapitools.client.models.GetFixedDepositProductsCurrency
import org.openapitools.client.models.GetFixedDepositProductsInterestCalculationDaysInYearType
import org.openapitools.client.models.GetFixedDepositProductsInterestCalculationType
import org.openapitools.client.models.GetFixedDepositProductsInterestCompoundingPeriodType
import org.openapitools.client.models.GetFixedDepositProductsInterestPostingPeriodType
import org.openapitools.client.models.GetFixedDepositProductsMaxDepositTermType
import org.openapitools.client.models.GetFixedDepositProductsMinDepositTermType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * GetFixedDepositProductsResponse
 *
 * @param accountingRule 
 * @param currency 
 * @param description 
 * @param id 
 * @param interestCalculationDaysInYearType 
 * @param interestCalculationType 
 * @param interestCompoundingPeriodType 
 * @param interestPostingPeriodType 
 * @param maxDepositTerm 
 * @param maxDepositTermType 
 * @param minDepositTerm 
 * @param minDepositTermType 
 * @param name 
 * @param nominalAnnualInterestRate 
 * @param preClosurePenalApplicable 
 * @param shortName 
 */


data class GetFixedDepositProductsResponse (

    @Json(name = "accountingRule")
    val accountingRule: GetFixedDepositProductsAccountingRule? = null,

    @Json(name = "currency")
    val currency: GetFixedDepositProductsCurrency? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "interestCalculationDaysInYearType")
    val interestCalculationDaysInYearType: GetFixedDepositProductsInterestCalculationDaysInYearType? = null,

    @Json(name = "interestCalculationType")
    val interestCalculationType: GetFixedDepositProductsInterestCalculationType? = null,

    @Json(name = "interestCompoundingPeriodType")
    val interestCompoundingPeriodType: GetFixedDepositProductsInterestCompoundingPeriodType? = null,

    @Json(name = "interestPostingPeriodType")
    val interestPostingPeriodType: GetFixedDepositProductsInterestPostingPeriodType? = null,

    @Json(name = "maxDepositTerm")
    val maxDepositTerm: kotlin.Int? = null,

    @Json(name = "maxDepositTermType")
    val maxDepositTermType: GetFixedDepositProductsMaxDepositTermType? = null,

    @Json(name = "minDepositTerm")
    val minDepositTerm: kotlin.Int? = null,

    @Json(name = "minDepositTermType")
    val minDepositTermType: GetFixedDepositProductsMinDepositTermType? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "nominalAnnualInterestRate")
    val nominalAnnualInterestRate: kotlin.Double? = null,

    @Json(name = "preClosurePenalApplicable")
    val preClosurePenalApplicable: kotlin.Boolean? = null,

    @Json(name = "shortName")
    val shortName: kotlin.String? = null

) {


}

