/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.GetFloatingRatesRatePeriods

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * GetFloatingRatesFloatingRateIdResponse
 *
 * @param createdBy 
 * @param createdOn 
 * @param id 
 * @param isActive 
 * @param isBaseLendingRate 
 * @param modifiedBy 
 * @param modifiedOn 
 * @param name 
 * @param ratePeriods 
 */


data class GetFloatingRatesFloatingRateIdResponse (

    @Json(name = "createdBy")
    val createdBy: kotlin.String? = null,

    @Json(name = "createdOn")
    val createdOn: kotlin.String? = null,

    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "isActive")
    val isActive: kotlin.Boolean? = null,

    @Json(name = "isBaseLendingRate")
    val isBaseLendingRate: kotlin.Boolean? = null,

    @Json(name = "modifiedBy")
    val modifiedBy: kotlin.String? = null,

    @Json(name = "modifiedOn")
    val modifiedOn: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "ratePeriods")
    val ratePeriods: kotlin.collections.Set<GetFloatingRatesRatePeriods>? = null

) {


}

