/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.GetGroupsTemplateColumnHeaderData

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param applicationTableName 
 * @param columnHeaderData 
 * @param registeredTableName 
 */


data class GetGroupsTemplateDatatables (

    @Json(name = "applicationTableName")
    val applicationTableName: kotlin.String? = null,

    @Json(name = "columnHeaderData")
    val columnHeaderData: kotlin.collections.Set<GetGroupsTemplateColumnHeaderData>? = null,

    @Json(name = "registeredTableName")
    val registeredTableName: kotlin.String? = null

) {


}

