/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.GetInterestRateChartsChartIdChartSlabsAttributeName
import org.openapitools.client.models.GetInterestRateChartsChartIdChartSlabsConditionType
import org.openapitools.client.models.GetInterestRateChartsChartIdChartSlabsEntityType
import org.openapitools.client.models.GetInterestRateChartsChartIdChartSlabsIncentiveType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param amount 
 * @param attributeName 
 * @param attributeValue 
 * @param attributeValueDesc 
 * @param conditionType 
 * @param entityType 
 * @param id 
 * @param incentiveType 
 */


data class GetInterestRateChartsChartIdChartSlabsIncentives (

    @Json(name = "amount")
    val amount: kotlin.Float? = null,

    @Json(name = "attributeName")
    val attributeName: GetInterestRateChartsChartIdChartSlabsAttributeName? = null,

    @Json(name = "attributeValue")
    val attributeValue: kotlin.Int? = null,

    @Json(name = "attributeValueDesc")
    val attributeValueDesc: kotlin.String? = null,

    @Json(name = "conditionType")
    val conditionType: GetInterestRateChartsChartIdChartSlabsConditionType? = null,

    @Json(name = "entityType")
    val entityType: GetInterestRateChartsChartIdChartSlabsEntityType? = null,

    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "incentiveType")
    val incentiveType: GetInterestRateChartsChartIdChartSlabsIncentiveType? = null

) {


}

