/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param code 
 * @param contra 
 * @param description 
 * @param disbursement 
 * @param externalId 
 * @param externalLoanId 
 * @param id 
 * @param loanId 
 * @param recoveryRepayment 
 * @param repayment 
 * @param repaymentAtDisbursement 
 * @param waiveCharges 
 * @param waiveInterest 
 * @param writeOff 
 */


data class GetLoansType (

    @Json(name = "code")
    val code: kotlin.String? = null,

    @Json(name = "contra")
    val contra: kotlin.Boolean? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "disbursement")
    val disbursement: kotlin.Boolean? = null,

    @Json(name = "externalId")
    val externalId: kotlin.String? = null,

    @Json(name = "externalLoanId")
    val externalLoanId: kotlin.String? = null,

    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "loanId")
    val loanId: kotlin.Long? = null,

    @Json(name = "recoveryRepayment")
    val recoveryRepayment: kotlin.Boolean? = null,

    @Json(name = "repayment")
    val repayment: kotlin.Boolean? = null,

    @Json(name = "repaymentAtDisbursement")
    val repaymentAtDisbursement: kotlin.Boolean? = null,

    @Json(name = "waiveCharges")
    val waiveCharges: kotlin.Boolean? = null,

    @Json(name = "waiveInterest")
    val waiveInterest: kotlin.Boolean? = null,

    @Json(name = "writeOff")
    val writeOff: kotlin.Boolean? = null

) {


}

