/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.GetRecurringDepositAccountsAccountChart
import org.openapitools.client.models.GetRecurringDepositAccountsCurrency
import org.openapitools.client.models.GetRecurringDepositAccountsDepositPeriodFrequency
import org.openapitools.client.models.GetRecurringDepositAccountsInterestCalculationDaysInYearType
import org.openapitools.client.models.GetRecurringDepositAccountsInterestCalculationType
import org.openapitools.client.models.GetRecurringDepositAccountsInterestCompoundingPeriodType
import org.openapitools.client.models.GetRecurringDepositAccountsInterestPostingPeriodType
import org.openapitools.client.models.GetRecurringDepositAccountsMaxDepositTermType
import org.openapitools.client.models.GetRecurringDepositAccountsMinDepositTermType
import org.openapitools.client.models.GetRecurringDepositAccountsRecurringDepositFrequencyType
import org.openapitools.client.models.GetRecurringDepositAccountsStatus
import org.openapitools.client.models.GetRecurringDepositAccountsSummary
import org.openapitools.client.models.GetRecurringDepositAccountsTimeline

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * GetRecurringDepositAccountsAccountIdResponse
 *
 * @param accountChart 
 * @param accountNo 
 * @param clientId 
 * @param clientName 
 * @param currency 
 * @param depositPeriod 
 * @param depositPeriodFrequency 
 * @param expectedFirstDepositOnDate 
 * @param externalId 
 * @param fieldOfficerId 
 * @param id 
 * @param interestCalculationDaysInYearType 
 * @param interestCalculationType 
 * @param interestCompoundingPeriodType 
 * @param interestPostingPeriodType 
 * @param maxDepositTerm 
 * @param maxDepositTermType 
 * @param minDepositTerm 
 * @param minDepositTermType 
 * @param preClosurePenalApplicable 
 * @param recurringDepositAmount 
 * @param recurringDepositFrequency 
 * @param recurringDepositFrequencyType 
 * @param savingsProductId 
 * @param savingsProductName 
 * @param status 
 * @param summary 
 * @param timeline 
 */


data class GetRecurringDepositAccountsAccountIdResponse (

    @Json(name = "accountChart")
    val accountChart: GetRecurringDepositAccountsAccountChart? = null,

    @Json(name = "accountNo")
    val accountNo: kotlin.Long? = null,

    @Json(name = "clientId")
    val clientId: kotlin.Long? = null,

    @Json(name = "clientName")
    val clientName: kotlin.String? = null,

    @Json(name = "currency")
    val currency: GetRecurringDepositAccountsCurrency? = null,

    @Json(name = "depositPeriod")
    val depositPeriod: kotlin.Int? = null,

    @Json(name = "depositPeriodFrequency")
    val depositPeriodFrequency: GetRecurringDepositAccountsDepositPeriodFrequency? = null,

    @Json(name = "expectedFirstDepositOnDate")
    val expectedFirstDepositOnDate: java.time.LocalDate? = null,

    @Json(name = "externalId")
    val externalId: kotlin.String? = null,

    @Json(name = "fieldOfficerId")
    val fieldOfficerId: kotlin.Long? = null,

    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "interestCalculationDaysInYearType")
    val interestCalculationDaysInYearType: GetRecurringDepositAccountsInterestCalculationDaysInYearType? = null,

    @Json(name = "interestCalculationType")
    val interestCalculationType: GetRecurringDepositAccountsInterestCalculationType? = null,

    @Json(name = "interestCompoundingPeriodType")
    val interestCompoundingPeriodType: GetRecurringDepositAccountsInterestCompoundingPeriodType? = null,

    @Json(name = "interestPostingPeriodType")
    val interestPostingPeriodType: GetRecurringDepositAccountsInterestPostingPeriodType? = null,

    @Json(name = "maxDepositTerm")
    val maxDepositTerm: kotlin.Int? = null,

    @Json(name = "maxDepositTermType")
    val maxDepositTermType: GetRecurringDepositAccountsMaxDepositTermType? = null,

    @Json(name = "minDepositTerm")
    val minDepositTerm: kotlin.Int? = null,

    @Json(name = "minDepositTermType")
    val minDepositTermType: GetRecurringDepositAccountsMinDepositTermType? = null,

    @Json(name = "preClosurePenalApplicable")
    val preClosurePenalApplicable: kotlin.Boolean? = null,

    @Json(name = "recurringDepositAmount")
    val recurringDepositAmount: kotlin.Int? = null,

    @Json(name = "recurringDepositFrequency")
    val recurringDepositFrequency: kotlin.Int? = null,

    @Json(name = "recurringDepositFrequencyType")
    val recurringDepositFrequencyType: GetRecurringDepositAccountsRecurringDepositFrequencyType? = null,

    @Json(name = "savingsProductId")
    val savingsProductId: kotlin.Long? = null,

    @Json(name = "savingsProductName")
    val savingsProductName: kotlin.String? = null,

    @Json(name = "status")
    val status: GetRecurringDepositAccountsStatus? = null,

    @Json(name = "summary")
    val summary: GetRecurringDepositAccountsSummary? = null,

    @Json(name = "timeline")
    val timeline: GetRecurringDepositAccountsTimeline? = null

) {


}

