/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ExternalId

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param dateFormat 
 * @param externalId 
 * @param hierarchy 
 * @param id 
 * @param locale 
 * @param name 
 * @param nameDecorated 
 * @param openingDate 
 * @param parentId 
 * @param parentName 
 * @param rowIndex 
 */


data class OfficeData (

    @Json(name = "dateFormat")
    val dateFormat: kotlin.String? = null,

    @Json(name = "externalId")
    val externalId: ExternalId? = null,

    @Json(name = "hierarchy")
    val hierarchy: kotlin.String? = null,

    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "locale")
    val locale: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "nameDecorated")
    val nameDecorated: kotlin.String? = null,

    @Json(name = "openingDate")
    val openingDate: java.time.LocalDate? = null,

    @Json(name = "parentId")
    val parentId: kotlin.Long? = null,

    @Json(name = "parentName")
    val parentName: kotlin.String? = null,

    @Json(name = "rowIndex")
    val rowIndex: kotlin.Int? = null

) {


}

