/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * PostOfficesRequest
 *
 * @param dateFormat 
 * @param externalId 
 * @param locale 
 * @param name 
 * @param openingDate 
 * @param parentId 
 */


data class PostOfficesRequest (

    @Json(name = "dateFormat")
    val dateFormat: kotlin.String? = null,

    @Json(name = "externalId")
    val externalId: kotlin.String? = null,

    @Json(name = "locale")
    val locale: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "openingDate")
    val openingDate: java.time.LocalDate? = null,

    @Json(name = "parentId")
    val parentId: kotlin.Long? = null

) {


}

