/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * PostClientCollateralRequest
 *
 * @param collateralId 
 * @param locale 
 * @param quantity 
 */


data class PostClientCollateralRequest (

    @Json(name = "collateralId")
    val collateralId: kotlin.Long? = null,

    @Json(name = "locale")
    val locale: kotlin.String? = null,

    @Json(name = "quantity")
    val quantity: java.math.BigDecimal? = null

) {


}

