/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * UpdatePostDatedCheckRequest
 *
 * @param accountNo 
 * @param amount 
 * @param date 
 * @param dateFormat 
 * @param locale 
 * @param name 
 * @param repaymentDate 
 */


data class UpdatePostDatedCheckRequest (

    @Json(name = "accountNo")
    val accountNo: kotlin.Long? = null,

    @Json(name = "amount")
    val amount: java.math.BigDecimal? = null,

    @Json(name = "date")
    val date: java.time.LocalDate? = null,

    @Json(name = "dateFormat")
    val dateFormat: kotlin.String? = null,

    @Json(name = "locale")
    val locale: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "repaymentDate")
    val repaymentDate: java.time.LocalDate? = null

) {


}

