/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.UpdateChangesResponse

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * UpdatePostDatedCheckResponse
 *
 * @param changes 
 * @param resourceId 
 */


data class UpdatePostDatedCheckResponse (

    @Json(name = "changes")
    val changes: UpdateChangesResponse? = null,

    @Json(name = "resourceId")
    val resourceId: kotlin.Int? = null

) {


}

